### ISSUE TITLE
simple code with conditional directives won't compile

### ISSUE THREAD

**Issue by slyshykO** [kant2002/FSharpPacker#14]
This code won't compile

```fsharp
#if INTERACTIVE
printfn "INTERACTIVE"
#else
printfn "NOT INTERACTIVE"
#endif
```

**Comment by kant2002** [comment]
I assume that you want to disambiguate compiled to EXE and  regular FSX files. As we discuss in Telegram channel, I propose to add `COMPILED_INTERACTIVE` which would be defined by FSharpPacker.
```fsharp
// some FSX file.
#if COMPILED_INTERACTIVE
printfn "INTERACTIVE"
#else
printfn "NOT INTERACTIVE"
#endif

```
